#!/usr/bin/env python3
"""
train_neuroswipe_v1.py

Stage 2: Main NeuroSwipe Transformer Classifier
------------------------------------------------
Trains the 4-layer Transformer Encoder-Decoder model to decode continuous swipe
trajectories into ranked character sequences / word candidates.

Data Sources:
- FUTO human swipes dataset (futo_swipes.parquet)
- High-fidelity synthetic supplemental swipes (generated by Seq2Traj for 6,842 words)

Target Output:
- Checkpoints saved to: models/neuroswipe_v1_best.pt
- Exported ONNX format: models/neuroswipe_v1.onnx
- Exported ExecuTorch:  models/neuroswipe_v1.pte
"""

import os
import sys
import json
import math
import argparse
from pathlib import Path
from typing import List, Tuple, Dict

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

# =============================================================================
# MODEL ARCHITECTURE: 4-Layer Transformer Encoder-Decoder
# =============================================================================

D_MODEL = 128
NUM_HEADS = 4
NUM_ENCODER_LAYERS = 4
NUM_DECODER_LAYERS = 4
DIM_FEEDFORWARD = 128
DROPOUT = 0.1

class SinusoidalPositionalEncoding(nn.Module):
    def __init__(self, d_model: int, max_len: int = 100):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        return x + self.pe[:, :x.size(1), :]

class NeuroSwipeTransformer(nn.Module):
    """
    On-device Transformer model for decoding touch trajectories into words.
    """
    def __init__(self, num_classes=30, input_feats=7):
        super().__init__()
        # Input trajectory feature projection
        self.traj_proj = nn.Linear(input_feats, D_MODEL)
        self.pos_encoder = SinusoidalPositionalEncoding(D_MODEL)
        
        # Transformer Encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=D_MODEL, nhead=NUM_HEADS, dim_feedforward=DIM_FEEDFORWARD,
            dropout=DROPOUT, activation=F.relu, batch_first=True
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=NUM_ENCODER_LAYERS)
        
        # Target Character Embeddings + Positional Encoding
        self.char_embed = nn.Embedding(num_classes, D_MODEL)
        self.char_pos_encoder = SinusoidalPositionalEncoding(D_MODEL)
        
        # Transformer Decoder
        decoder_layer = nn.TransformerDecoderLayer(
            d_model=D_MODEL, nhead=NUM_HEADS, dim_feedforward=DIM_FEEDFORWARD,
            dropout=DROPOUT, activation=F.relu, batch_first=True
        )
        self.decoder = nn.TransformerDecoder(decoder_layer, num_layers=NUM_DECODER_LAYERS)
        
        # Output Linear Head
        self.out_head = nn.Linear(D_MODEL, num_classes)

    def encode(self, traj_feats, traj_mask=None):
        x = self.traj_proj(traj_feats)
        x = self.pos_encoder(x)
        padding_mask = ~traj_mask if traj_mask is not None else None
        return self.encoder(x, src_key_padding_mask=padding_mask)

    def decode(self, tgt_tokens, memory, memory_mask=None, tgt_mask=None):
        y = self.char_embed(tgt_tokens)
        y = self.char_pos_encoder(y)
        seq_len = tgt_tokens.size(1)
        causal_mask = nn.Transformer.generate_square_subsequent_mask(seq_len).to(tgt_tokens.device)
        padding_mask = ~memory_mask if memory_mask is not None else None
        
        dec_out = self.decoder(y, memory, tgt_mask=causal_mask, memory_key_padding_mask=padding_mask)
        return self.out_head(dec_out)

    def forward(self, traj_feats, tgt_tokens, traj_mask=None):
        memory = self.encode(traj_feats, traj_mask)
        return self.decode(tgt_tokens, memory, traj_mask)

if __name__ == "__main__":
    print("NeuroSwipe Transformer Model definition ready.")
