package dev.patrickgold.florisboard.ime.nlp.shared

import android.content.Context
import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader

/**
 * Personal phrase predictions learned from typing history (harvest data).
 * Mirrors BigramTable's singleton pattern.
 *
 * Key: 2-word context (lowercase, space-joined), e.g. "i'll be"
 * Value: list of continuations ranked by frequency, e.g. ["there in a minute", "right back"]
 *
 * Data source: personal_phrases.tsv generated by harvest_analyze.py
 * Format: word1 word2\tcontinuation\tfrequency (tab-separated)
 */
class PhraseTable private constructor(
    private val table: Map<String, List<Pair<String, Int>>>
) {
    /**
     * Predict continuations for a 2-word context.
     * @param word1 First word of the context
     * @param word2 Second word of the context
     * @param max Maximum number of predictions to return
     * @return List of continuation strings ranked by frequency
     */
    fun predictContinuation(word1: String, word2: String, max: Int = 3): List<String> {
        val key = "${word1.lowercase()} ${word2.lowercase()}"
        return table[key]?.take(max)?.map { it.first } ?: emptyList()
    }

    fun getPhraseCount(): Int = table.size

    companion object {
        private const val TAG = "PhraseTable"
        private const val PHRASE_ASSET_PATH = "ime/dict/personal_phrases.tsv"

        @Volatile
        private var instance: PhraseTable? = null
        private var lastError: String? = null

        fun get(): PhraseTable? = instance

        fun getLastError(): String? = lastError

        /**
         * Load personal phrases from the asset path. Fails silently if file doesn't exist.
         */
        fun load(context: Context) {
            try {
                val stream = context.assets.open(PHRASE_ASSET_PATH)
                instance = fromStream(stream)
                android.util.Log.i(TAG, "Loaded PhraseTable with ${instance?.table?.size ?: 0} phrase contexts")
            } catch (e: java.io.FileNotFoundException) {
                // Expected when personal_phrases.tsv hasn't been generated yet
                android.util.Log.i(TAG, "No personal_phrases.tsv found (expected on first run)")
            } catch (e: Exception) {
                lastError = "${e::class.simpleName}: ${e.message}"
                android.util.Log.e(TAG, "Failed to load PhraseTable", e)
            }
        }

        /**
         * Load phrases from an input stream.
         * Format: word1 word2\tcontinuation\tfrequency
         */
        fun fromStream(stream: InputStream): PhraseTable {
            val raw = mutableMapOf<String, MutableList<Pair<String, Int>>>()

            BufferedReader(InputStreamReader(stream)).useLines { lines ->
                lines.forEach { line ->
                    val parts = line.split('\t')
                    if (parts.size < 3) return@forEach
                    val context = parts[0].lowercase().trim()
                    val continuation = parts[1].trim()
                    val freq = parts[2].toIntOrNull() ?: return@forEach
                    if (context.isBlank() || continuation.isBlank()) return@forEach

                    val entries = raw.getOrPut(context) { mutableListOf() }
                    entries.add(continuation to freq)
                }
            }

            // Sort each context's continuations by frequency (descending)
            val table = raw.mapValues { (_, entries) ->
                entries.sortedByDescending { it.second }
            }

            return PhraseTable(table)
        }
    }
}
